### ISSUE TITLE
[Releases] Latest executable file for windows doesn't  work well

### ISSUE THREAD

**Issue by Dokman** [redbaty/Wasari#2]
![image](https://user-images.githubusercontent.com/2290904/147136700-af9aace6-e9b0-413d-b3af-2a3f55b93a28.png)

**Comment by mvmcjr** [comment]
Which build was it, is it on #36?

**Comment by Dokman** [comment]
yes

**Comment by mvmcjr** [comment]
Huh thats weird, I've just created a VM and it worked. Can you share the url you're trying to download?

**Comment by Dokman** [comment]
i'm using my tower to use it and i compiled it and i have this error now
![image](https://user-images.githubusercontent.com/2290904/147156935-b7393012-0cff-4d59-b621-2c51a3a6be14.png)

**Comment by mvmcjr** [comment]
Yeah that part I understood, but I can't reproduce it, that why I'm asking you for the series URL, so I can try to reproduce it.

**Comment by Dokman** [comment]
oh yes https://www.crunchyroll.com/es-es/the-worlds-finest-assassin-gets-reincarnated-in-another-world-as-an-aristocrat

**Comment by Dokman** [comment]
i was testing without headless and i'm having the same problem so might be something that we don't know

**Comment by mvmcjr** [comment]
Can you try and start it with the argument `--headless false` and check if chromium gets stuck somewhere?

**Comment by Dokman** [comment]
i've compiled in code is the same but i ended with the same result

**Comment by mvmcjr** [comment]
I meant --headless false as an argument, or edit BrowserFactory.cs on line 18 and change headless to false

**Comment by Dokman** [comment]
> I meant --headless false as an argument, or edit BrowserFactory.cs on line 18 and change headless to false

I've done that yesterday and t'he result was the same

**Comment by mvmcjr** [comment]
And where does chromium gets stuck?

**Comment by Dokman** [comment]
It login but when is trying to download It vives me a timeout

**Comment by mvmcjr** [comment]
It logs in normally? Closes the tab and all?

**Comment by Dokman** [comment]
> It logs in normally? Closes the tab and all?

yes and then i have the timeout

**Comment by mvmcjr** [comment]
Ahmm it shouldn't have closed any tabs, since by your screenshot it is waiting for chromium to navigate somewhere. 
After it types in your credentials and press the login button, where does chromium stays?

**Comment by Dokman** [comment]
if i do not close it i'm having this error
![image](https://user-images.githubusercontent.com/2290904/147272796-31937ca9-1979-4132-bc88-98a2fa7962c7.png)

**Comment by Dokman** [comment]
i'm having this without closing anything
![image](https://user-images.githubusercontent.com/2290904/147272936-d712fff2-5557-4108-986f-9963acc6df59.png)

**Comment by mvmcjr** [comment]
Huh that weird, the JSON containing the media ID is malformed:

![image](https://user-images.githubusercontent.com/4898202/147274732-6bbab568-0e4a-4882-861f-b6de2699da19.png)

I've changed it to use regex instead of JSON parsing, can you try the latest build and print the results again?

**Comment by Dokman** [comment]
> Huh that weird, the JSON containing the media ID is malformed:
> 
> ![image](https://user-images.githubusercontent.com/4898202/147274732-6bbab568-0e4a-4882-861f-b6de2699da19.png)
> 
> I've changed it to use regex instead of JSON parsing, can you try the latest build and print the results again?

as latest build i'm having this issue
![image](https://user-images.githubusercontent.com/2290904/147279772-0e95bb90-8d39-4710-975d-a8b620a23792.png)

**Comment by mvmcjr** [comment]
I've just released another build which skips the API authentication if not necessary (which is your case), can you try again with build #40?

**Comment by Dokman** [comment]
The same
![image](https://user-images.githubusercontent.com/2290904/147281313-1725b283-f74c-4631-b240-b994f1c9bb24.png)

**Comment by mvmcjr** [comment]
Oops, I had mixed up the rules, can you try again on #41?

**Comment by Dokman** [comment]
Now they say that my credentials where not provided and were provided
![image](https://user-images.githubusercontent.com/2290904/147287599-3bc8fcea-3703-4c62-bb27-d37894320be2.png)

**Comment by mvmcjr** [comment]
Fixed that too, can you try on #42?

**Comment by Dokman** [comment]
![image](https://user-images.githubusercontent.com/2290904/147289983-39184f67-3316-4d3d-83de-1f5924743eb9.png)
Finally working
