### ISSUE TITLE
I run the command and it gives me this error

### ISSUE THREAD

**Issue by manbug10** [redbaty/Wasari#20]
El sistema no puede encontrar el texto del mensaje para el mensaje número 0x2350 en el archivo de mensajes para Application.

(c) Microsoft Corporation. Todos los derechos reservados.

D:\bin>wasari.cli -h
 __        __                   _
 \ \      / /_ _ ___  __ _ _ __(_)
  \ \ /\ / / _` / __|/ _` | '__| |
   \ V  V / (_| \__ \ (_| | |  | |
    \_/\_/ \__,_|___/\__,_|_|  |_|

Current version: 1.0.17.0
Available environment features: "YtDlp", "Ffmpeg", "FfmpegLibPlacebo", "NvidiaGpu"
Unhandled exception. System.InvalidOperationException: Failed to infer the default application executable name. Please specify it explicitly using SetExecutableName().
   at CliFx.CliApplicationBuilder.GetDefaultExecutableName() in /_/CliFx/CliApplicationBuilder.cs:line 246
   at CliFx.CliApplicationBuilder.Build() in /_/CliFx/CliApplicationBuilder.cs:line 201
   at Wasari.Cli.Program.Main()
   at Wasari.Cli.Program.<Main>()

D:\bin>

**Comment by manbug10** [comment]
any solution?

**Comment by mvmcjr** [comment]
Should be fixed in the [latest release](https://github.com/redbaty/Wasari/releases/tag/latest)
