### ISSUE TITLE
[Idea] Config file to certainly not use a lot of arguments

### ISSUE THREAD

**Issue by Dokman** [redbaty/Wasari#3]
A posible idea to make it can be a config file because a lot of users don't know anything about arguments or complicated arguments

**Comment by mvmcjr** [comment]
Hmm I don't think this is currently on scope, the idea of this project is to be an interface, and for example to be use later by another project to create a GUI, Web app or whatever.

So for now I guess we'll have to stick to arguments :(

**Comment by Dokman** [comment]
i can create a WPF interface :)
