### ISSUE TITLE
Download file mask support

### ISSUE THREAD

**Issue by MoustafaMetawea** [redbaty/Wasari#4]
Can I download the series with the file name "attack on titan S04E01" instead of Attack on Titan (OmU) Folge 60 - Auf der anderen Seite des Meeres [799901]

**Comment by mvmcjr** [comment]
I've added support for file mask, usage for your case would be:

` -m "attack on titan {0}"`

**Comment by MoustafaMetawea** [comment]
I did like what you said but it shows yt-dlp: error: no such option: -m

yt-dlp --external-downloader aria2c -S "res:720,fps" https://www.crunchyroll.com/attack-on-titan -m "attack on titan {0}" --write-subs --embed-subs --sub-langs arME

**Comment by mvmcjr** [comment]
This is supported by Wasari, not by yt-dlp.

The equivalent would be something like:

`.\Wasari crunchy "https://www.crunchyroll.com/attack-on-titan" -f "best[height=720]" -m "attack on titan {0}"`

**Comment by MoustafaMetawea** [comment]
Is there another contact like telegram or skype I want to inquire about
things

‫في الخميس، 20 يناير 2022 في 3:50 ص تمت كتابة ما يلي بواسطة ‪Marcos
Cordeiro‬‏ ***@***.***‬‏>:‬
